version: '3'
services:
  api:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    command: >
     bash -c "chmod +x ./wait-for-it.sh
     && ./wait-for-it.sh eventstore:2113 -- node -r babel-register src/app dev"
    ports:
      - "3001:3001"
    expose:
      - "3001"
    depends_on:
      - eventstore
    environment:
      - LES_FORCE_RM_REBUILD

  eventstore: 
    image: eventstore/eventstore
    ports:
      - 2113:2113
